### ISSUE TITLE
Image Carousel Compatibility Issue

### ISSUE THREAD

**Issue by PooleHenry** [Orbiit/gunn-remake#16]
The images in the image carousel span only half the page on my browser (Safari, MacOS 10.10.5). 

User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

![screencap](http://i.imgur.com/eRl6S7n.png)

**Comment by SheepTester** [comment]
I know what the problem is.

When animating the image change, there are two elements within the same parent; one is the actual image you see, one is a `canvas` element that only shows when the animation happens.

However, the flexbox that the image centering relies on freaks out and tries to put the two elements next to each other; I tried fixing this by putting `position: absolute;` on one or both of the children.

It works on Chrome, Firefox, and Edge, so I'll be a tad bit disappointed if Safari can't handle it

@Velosify Does it not work on your Safari either?

Also, thanks for the image! 👍

**Comment by PooleHenry** [comment]
@SheepTester 

The `position: absolute;` property doesn't seem to do anything for me. I think it must be something with the margin because doing `margin: 0 auto;` seemed to work though. I'm not very experienced in CSS, so I made a pull request [here](https://github.com/Orbiit/gunn-remake/pull/17) so I wouldn't break the site with a commit.

**Comment by SheepTester** [comment]
Actually, it's because Safari doesn't follow [the latest version of "the spec"](https://developers.google.com/web/updates/2016/06/absolute-positioned-children) and so it still treats absolute positioned flexbox children as if they are 0 by 0

**Comment by PooleHenry** [comment]
@SheepTester 

Fixed! Thank you!
